---
- hosts: localhost
  tasks:
    - name: Include and run tasks
      include_tasks: "{{ item }}"
      loop: "{{ query('fileglob', \"*.yml\", wantlist=true) | reject('search','playbook.yml') | list | sort }}"
